filebeat.inputs:
- type: stdin
  # fields:
  #   apache: true
  # fields_under_root: true
  json:
  - keys_under_root: true
  - overwrite_keys: true
  - add_error_key: true
  - message_key: log
processors:
 - drop_fields:
    fields: ["@timestamp", "@metadata", "host", "agent", "log", "input", "ecs"]
    # ignore_missing: true
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["kafka:9092"]

  # message topic selection + partitioning
  topic: "test"
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  # compression: gzip
  max_message_bytes: 1000000
  